// SPDX-License-Identifier: GPL-3.0-only
// Copyright (c) 2024-2026 Friehub. All rights reserved.
// Commercial use requires a separate license: https://friehub.com/licensing

//! Phase 4: Function Summaries
//!
//! This module solves the Interprocedural Leaking (Context-Insensitivity)
//! problem. Instead of jumping into functions and merging everyone's memory
//! together, we analyze a function ONCE and produce a mathematical summary
//! of how inputs flow to outputs and memory.

use crate::ir::function::*;
use rustc_hash::FxHashMap;

/// Describes how data flows from inputs (Parameters/Heap) to outputs (Return/Heap)
#[derive(Debug, Clone)]
#[cfg_attr(feature = "serialize", derive(serde::Serialize, serde::Deserialize))]
pub struct FunctionSummary {
    pub function_name: String,

    /// Maps the function's return value to the parameters that taint it.
    /// Example: `return req.body;` -> `returns_tainted_by = [0]` (Param 0)
    pub returns_tainted_by_params: Vec<usize>,

    /// Identifies if the function mutates an object passed into it.
    /// Example: `function init(obj) { obj.ready = true; }`
    /// Maps Param Index -> List of mutated fields
    pub mutates_param_fields: FxHashMap<usize, Vec<String>>,

    /// Identifies if the function reads a parameter and passes it to a known dangerous Sink.
    /// Example: `function runQuery(sql) { db.execute(sql); }` -> `sink_params = [0]`
    pub sinks_params: Vec<usize>,
}

impl FunctionSummary {
    /// Applies this summary at a CallSite to immediately propagate taint
    /// without needing to analyze the function body again.
    pub fn apply_to_callsite(
        &self,
        _ir: &mut FunctionIR,
        _call_instr: &Instruction,
        _current_mem_state: VarId,
    ) -> Option<VarId> {
        // In a full implementation, this logic reads `CallStatic` arguments,
        // cross-references `returns_tainted_by_params`, and directly aliases
        // the returned `dest` variable to the tainted arguments in the local Points-To Graph.

        // Return the new memory state generated by the function call (if it mutates objects)
        None
    }
}

/// A registry that holds summaries for all functions across the corpus.
#[derive(Debug, Default)]
pub struct SummaryRegistry {
    pub summaries: FxHashMap<String, FunctionSummary>,
}

impl SummaryRegistry {
    pub fn new() -> Self {
        Self {
            summaries: FxHashMap::default(),
        }
    }

    pub fn register(&mut self, summary: FunctionSummary) {
        self.summaries
            .insert(summary.function_name.clone(), summary);
    }
}
